---
- name: Install essential infra tools on Windows
  hosts: all
  gather_facts: no
  become: false

  vars:
    download_dir: 'C:\Temp\tools'

  pre_tasks:

    - name: Create local tools directory
      win_file:
        path: "{{ download_dir }}"
        state: directory

    - name: Download PuTTY installer
      win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-installer.msi
        dest: "{{ download_dir }}\\putty-64bit-installer.msi"

    - name: Download 7-Zip
      win_get_url:
        url: https://www.7-zip.org/a/7z2301-x64.exe
        dest: "{{ download_dir }}\\7z.exe"

    - name: Download Notepad++
      win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.4/npp.8.6.4.Installer.x64.exe
        dest: "{{ download_dir }}\\npp.exe"

    - name: Download Git for Windows
      win_get_url:
        url: https://github.com/git-for-windows/git/releases/download/v2.44.0.windows.1/Git-2.44.0-64-bit.exe
        dest: "{{ download_dir }}\\git-installer.exe"

    - name: Download WinSCP
      win_get_url:
        url: https://winscp.net/download/WinSCP-6.1.2-Setup.exe
        dest: "{{ download_dir }}\\winscp.exe"

  tasks:

    - name: Install PuTTY
      win_package:
        path: "{{ download_dir }}\\putty-64bit-installer.msi"
        arguments: /quiet

    - name: Install 7-Zip
      win_package:
        path: "{{ download_dir }}\\7z.exe"
        arguments: /S

    - name: Install Notepad++
      win_package:
        path: "{{ download_dir }}\\npp.exe"
        arguments: /S

    - name: Install Git
      win_package:
        path: "{{ download_dir }}\\git-installer.exe"
        arguments: /VERYSILENT

    - name: Install WinSCP
      win_package:
        path: "{{ download_dir }}\\winscp.exe"
        arguments: /silent
